config/routes.rb
Rails.application.routes.draw do
  root 'news#index'
  resources :news, only: [:index, :show]
  resources :channels, expect: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :news, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :url, presence: true, uniqueness: true,
                  format: /\A(http|https):\/\/[a-z0-9]+([\-.]{1}[a-z0-9]+)*\.[a-z]{2,63}(:[0-9]{1,5})?(\/.*)?\z/ix, http_url: true
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :channel

  validates :title, presence: true, length: { minimum: 3 }
  validates :link, presence: true, format: /\A(http|https):\/\/[a-z0-9]+([\-.]{1}[a-z0-9]+)*\.[a-z]{2,63}(:[0-9]{1,5})?(\/.*)?\z/ix
  validates :description, presence: true
  validates :pubdate, presence: true, numericality: { only_integer: true }
  validates :channel, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:edit, :update, :destroy]

  def index
    @channels = Channel.all
  end

  def new
    @channel = Channel.new
  end

  def edit; end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      redirect_to(channels_url, notice: 'Channel was successfully created.')
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def update
    if @channel.update(channel_params)
      redirect_to(channels_url, notice: 'Channel was successfully updated.')
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def destroy
    @channel.destroy
    redirect_to(channels_url, notice: 'Channel was successfully destroyed.')
  end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end

  def channel_params
    params.require(:channel).permit(:title, :url)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  include NewsHelper
  before_action :set_news, only: [:show]

  def index
    @channels = Channel.all
    get_news
    @news = News.paginate(page: params[:page], per_page: 20).order(pubdate: :desc)
  end

  def show
    @news.looked = true
    @news.save
  end

  private

  def set_news
    @news = News.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete(:current_page)

    css_class = current_page == title ? 'button-active' : ''

    options[:class] = if options[:class]
                        options[:class] + ' ' + css_class
                      else
                        css_class
                      end

    link_to(title, url, options)
  end

  def currently_at(current_page = '')
    render(partial: 'shared/menu', locals: { current_page: current_page })
  end

  def full_title(page_title = '')
    base_title = 'RSS reader'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/news_helper.rb
module NewsHelper
  def get_news
    channels = Channel.all
    channels.each do |channel|
      NewsGetter.(url: channel.url, id: channel.id)
    end
  end
end

app/views/channels/_form_create.html.slim
= form_for @channel do |f|
  .mb-3
    = f.text_field :title, class: "form-control form-title", placeholder: 'Enter the channel name'

  .mb-3
    = f.text_field :url, class: "form-control form-url", placeholder: 'Enter the channel URL. Example: https://meduza.io/rss/all'

  .actions 
    = link_to "Back", channels_path, class: "btn btn-sm btn-secondary"
    |  | 
    = f.submit "Create channel", class: "btn btn-sm btn-success"

app/views/channels/_form_update.html.slim
= form_for @channel do |f|
  .mb-3
    = f.text_field :title, class: "form-control form-title", placeholder: 'Enter the channel name'

  .mb-3
    = f.text_field :url, class: "form-control form-url", placeholder: 'Enter the channel URL'

  .actions 
    = link_to "Back", channels_path, class: "btn btn-sm btn-secondary"
    |  | 
    = f.submit "Update channel", class: "btn btn-sm btn-success"

app/views/channels/edit.html.slim
= provide :page_title, "Edit channel"
= currently_at 'Channels'

h1.title-pozition Editing channel

== render "form_update"

app/views/channels/index.html.slim
= provide :page_title, "Channels"
= currently_at 'Channels'

h1.title-pozition RSS channels

= link_to "Add Channel", new_channel_path, class: 'btn btn-success btn-sm'

table.table
  thead
    tr
      th[scope="col"]
        |
      th[scope="col"]
        |
      th[scope="col"]
        | 
      th[scope="col"]
        |
  tbody
    - @channels.each_with_index do |channel, index|
      tr
        td[scope="row"] = index + 1
        td = channel.title
        td = link_to channel.url, channel.url, target: "_blank"
        td[class="table-btn"]   
          = link_to image_tag('edit.svg', class: 'btn-icon-sm'), edit_channel_path(channel), class: 'btn-style-edit', title: 'Edit'
          = link_to image_tag('trash-2.svg', class: 'btn-icon-sm'), channel, title: 'Delete', class: 'btn-style-delete', method: :delete, data: {confirm: "Are you sure?"} 
      tr

app/views/channels/new.html.slim
= provide :page_title, "New channel"
= currently_at 'Channels'

h1.title-pozition New channel

== render "form_create"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:page_title))
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    .container
      div data-controller="toggle"
        = yield :main_menu
      = yield

app/views/news/index.html.slim
= provide :page_title, "News"
= currently_at 'News'

h1.title-pozition RSS news

.notice
  div
    = link_to "Add Channel", new_channel_path, class: 'btn btn-success btn-sm'
  .message
    - if !@channels.empty? && @news.empty?
      | Check channels URL !!!

hr

.news-container
  div data-controller="sidebar"
    .sidebar id="sidebar" data-sidebar-target="sidebarNav"
      - @channels.each do |channel|
        .channel
          = image_tag('rss.svg')    
          = channel.title
  .news
    - @news.each do |news|
      .card
        .card-title-style
          = link_to news_path(news) do
            - if news.looked 
              p.card-header
                = news[:title]
            - else
              h5.card-header
                = news[:title]
            .card-header.data
              div 
                = news.channel.title
              div  
                = Time.at(news[:pubdate]).strftime("%Y-%m-%d %H:%M:%S")

br

.digg_pagination
  = will_paginate @news, :container => false

app/views/news/show.html.slim
= provide :page_title, "Show news"
= currently_at 'News'

.one_news_container
  h3
    = @news.title

  p
    = @news.description.html_safe

  p
    img src== @news.image_url

  p
    = @news.author 
    |  | 
    = Time.at(@news.pubdate).strftime("%Y-%m-%d %H:%M:%S")
  

  = link_to "Back", news_index_path, class: "btn btn-secondary btn-sm"
  |  |  
  = link_to "Original news", @news.link, class: "btn btn-success btn-sm", target: "_blank"

app/views/shared/_menu.html.slim
= provide :main_menu
  nav.navbar.navbar-expand-lg.navbar-light.bg-light.navbar-margin
    .container-fluid
      button.navbar-toggler[type="button" data-toggle="collapse" data-toggle-target="navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"]
        span.navbar-toggler-icon
      #navbarNavAltMarkup.collapse.navbar-collapse
        .navbar-nav
          = link_to image_tag("rss.svg"), root_path, class: 'logo'
          = nav_tab 'News', news_index_path, class: "nav-link", current_page: current_page
          = nav_tab 'Channels', channels_path, class: "nav-link", current_page: current_page